// export const CHECK_USER_ID_REQUEST = "USER/CHECK_USER_ID_REQUEST";
// export const CHECK_USER_ID_SUCCESS = "USER/CHECK_USER_ID_SUCCESS";
// export const CHECK_USER_ID_FAILURE = "USER/CHECK_USER_ID_FAILURE";

export const LOGIN_REQUEST = "USER/LOGIN_REQUEST";
export const LOGIN_SUCCESS = "USER/LOGIN_SUCCESS";
export const LOGIN_FAILURE = "USER/LOGIN_FAILURE";

export const REGISTER_REQUEST = "USER/REGISTER_REQUEST";
export const REGISTER_SUCCESS = "USER/REGISTER_SUCCESS";
export const REGISTER_FAILURE = "USER/REGISTER_FAILURE";

export const LOGOUT_REQUEST = "USER/LOGOUT_REQUEST";
export const LOGOUT_SUCCESS = "USER/LOGOUT_SUCCESS";
export const LOGOUT_FAILURE = "USER/LOGOUT_FAILURE";

export const USERS_DETAIL_REQUEST = "USER/USERS_DETAIL_REQUEST";
export const USERS_DETAIL_SUCCESS = "USER/USERS_DETAIL_SUCCESS";
export const USERS_DETAIL_FAILURE = "USER/USERS_DETAIL_FAILURE";

export const USER_DETAIL_REQUEST = "USER/USER_DETAIL_REQUEST";
export const USER_DETAIL_SUCCESS = "USER/USER_DETAIL_SUCCESS";
export const USER_DETAIL_FAILURE = "USER/USER_DETAIL_FAILURE";

export const USER_DETAIL_UPDATE_REQUEST = "USER/USER_DETAIL_UPDATE_REQUEST";
export const USER_DETAIL_UPDATE_SUCCESS = "USER/USER_DETAIL_UPDATE_SUCCESS";
export const USER_DETAIL_UPDATE_FAILURE = "USER/USER_DETAIL_UPDATE_FAILURE";

export const USER_CARD_UPDATE_FAILURE = "USER/USER_CARD_UPDATE_FAILURE";
export const USER_CARD_UPDATE_REQUEST = "USER/USER_CARD_UPDATE_REQUEST";
export const USER_CARD_UPDATE_SUCCESS = "USER/USER_CARD_UPDATE_SUCCESS";

export const FANS_INFO_LOAD_REQUEST = "FANS/FANS_INFO_LOAD_REQUEST";
export const FANS_INFO_LOAD_SUCCESS = "FANS/FANS_INFO_LOAD_SUCCESS";
export const FANS_INFO_LOAD_FAILURE = "FANS/FANS_INFO_LOAD_FAILURE";

export const FANS_INFO_SEND_REQUEST = "FANS/FANS_INFO_SEND_REQUEST";
export const FANS_INFO_SEND_SUCCESS = "FANS/FANS_INFO_SEND_SUCCESS";
export const FANS_INFO_SEND_FAILURE = "FANS/FANS_INFO_SEND_FAILURE";

export const FANS_INFO_ADD_REQUEST = "FANS/FANS_INFO_ADD_REQUEST";
export const FANS_INFO_ADD_SUCCESS = "FANS/FANS_INFO_ADD_SUCCESS";
export const FANS_INFO_ADD_FAILURE = "FANS/FANS_INFO_ADD_FAILURE";

export const FANS_INFO_UPDATE_REQUEST = "FANS/FANS_INFO_UPDATE_REQUEST";
export const FANS_INFO_UPDATE_SUCCESS = "FANS/FANS_INFO_UPDATE_SUCCESS";
export const FANS_INFO_UPDATE_FAILURE = "FANS/FANS_INFO_UPDATE_FAILURE";

export const FANS_INFO_DELETE_REQUEST = "FANS/FANS_INFO_DELETE_REQUEST";
export const FANS_INFO_DELETE_SUCCESS = "FANS/FANS_INFO_DELETE_SUCCESS";
export const FANS_INFO_DELETE_FAILURE = "FANS/FANS_INFO_DELETE_FAILURE";

export const FANS_POWER_REQUEST = "FANS/FANS_POWER_REQUEST";
export const FANS_POWER_SUCCESS = "FANS/FANS_POWER_SUCCESS";
export const FANS_POWER_FAILURE = "FANS/FANS_POWER_FAILURE";

export const MODULES_INFO_LOAD_REQUEST = "MODULES/MODULES_INFO_LOAD_REQUEST";
export const MODULES_INFO_LOAD_SUCCESS = "MODULES/MODULES_INFO_LOAD_SUCCESS";
export const MODULES_INFO_LOAD_FAILURE = "MODULES/MODULES_INFO_LOAD_FAILURE";

export const MODULES_INFO_SEND_REQUEST = "MODULES/MODULES_INFO_SEND_REQUEST";
export const MODULES_INFO_SEND_SUCCESS = "MODULES/MODULES_INFO_SEND_SUCCESS";
export const MODULES_INFO_SEND_FAILURE = "MODULES/MODULES_INFO_SEND_FAILURE";

export const MODULES_INFO_ADD_REQUEST = "MODULES/MODULES_INFO_ADD_REQUEST";
export const MODULES_INFO_ADD_SUCCESS = "MODULES/MODULES_INFO_ADD_SUCCESS";
export const MODULES_INFO_ADD_FAILURE = "MODULES/MODULES_INFO_ADD_FAILURE";

export const MODULES_INFO_UPDATE_REQUEST =
  "MODULES/MODULES_INFO_UPDATE_REQUEST";
export const MODULES_INFO_UPDATE_SUCCESS =
  "MODULES/MODULES_INFO_UPDATE_SUCCESS";
export const MODULES_INFO_UPDATE_FAILURE =
  "MODULES/MODULES_INFO_UPDATE_FAILURE";

export const MODULES_INFO_DELETE_REQUEST =
  "MODULES/MODULES_INFO_DELETE_REQUEST";
export const MODULES_INFO_DELETE_SUCCESS =
  "MODULES/MODULES_INFO_DELETE_SUCCESS";
export const MODULES_INFO_DELETE_FAILURE =
  "MODULES/MODULES_INFO_DELETE_FAILURE";

export const MODULE_SITES_INFO_LOAD_REQUEST =
  "MODULE_SITES/MODULE_SITES_INFO_LOAD_REQUEST";
export const MODULE_SITES_INFO_LOAD_SUCCESS =
  "MODULE_SITES/MODULE_SITES_INFO_LOAD_SUCCESS";
export const MODULE_SITES_INFO_LOAD_FAILURE =
  "MODULE_SITES/MODULE_SITES_INFO_LOAD_FAILURE";
